timeout: 3600s

options:
  env:
  - PROJECT_ID=$PROJECT_ID
  - WORKSPACE_LINK=/go/src/github.com/m-lab/locate

steps:
# Run unit tests for environment.
- name: gcr.io/$PROJECT_ID/golang-cbif
  env:
  - GONOPROXY=github.com/m-lab/go/*
  args:
  - go version
  - go get -v -t ./...
  - go vet ./...
  - go test ./... -race
  - go test -v ./...

# Deployment of platform specific APIs in sandbox & staging & mlab-ns.
# NOTE: these services are not meant for the public, e.g. /v2/platform/*
- name: gcr.io/$PROJECT_ID/gcloud-jsonnet-cbif
  env:
  # Use cbif condition: only run these steps in one of these projects.
  - PROJECT_IN=mlab-sandbox,mlab-staging,mlab-ns
  args:
  - cp cloudbuild/app-platform.yaml.$PROJECT_ID app.yaml
  - gcloud --project $PROJECT_ID app deploy --promote app.yaml

# Deployment of public APIs in sandbox & staging & mlab-ns. e.g. /v2/nearest/*
- name: gcr.io/$PROJECT_ID/gcloud-jsonnet-cbif
  env:
  # Use cbif condition: only run these steps in one of these projects.
  - PROJECT_IN=mlab-sandbox,mlab-staging,mlab-ns
  args:
  - cp cloudbuild/app.yaml.$PROJECT_ID app.yaml
  - gcloud --project $PROJECT_ID app deploy --promote app.yaml
