version: '3.8'
services:
    redis:
        image: redis:7.0.2-alpine
        ports:
            - '6379:6379'
        # Disable persistence. All state is only in RAM.
        command: redis-server --save ""
        restart: always

    locate:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        command:
            - -google-cloud-project=mlab-sandbox
            - -platform-project=mlab-sandbox
            - -port=8080
            - -redis-address=redis:6379
            - -prometheus-username-secret-name=./secrets/testdata/prom-auth-user
            - -prometheus-password-secret-name=./secrets/testdata/prom-auth-pass
            - -prometheus-url=https://prometheus-basicauth.mlab-sandbox.measurementlab.net/
            - -key-source=local
            - -signer-secret-name=./secrets/testdata/jwk_sig_EdDSA_test_20220415
            - -verify-secret-name=./secrets/testdata/jwk_sig_EdDSA_test_20220415.pub
            - -prometheusx.listen-address=:9090
