# [START swagger]
swagger: "2.0"
info:
  description: |-
    The Locate Platform API provides platform-specific, authenticated methods
    (e.g., for monitoring and heartbeats).
  title: "M-Lab Locate Platform API"
  version: "2.0.0"
host: "locate-platform-dot-{{PROJECT}}.appspot.com"
# [END swagger]

consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "ws"
- "wss"

paths:
  # Heartbeats WITH an API key.
  "/v2/platform/heartbeat":
    get:
      description: |-
        Report the health of an experiment instance.
      operationId: "v2-platform-heartbeat"
      responses:
        '200':
          description: OK.
      security:
      - api_key: []

securityDefinitions:
  # This section configures basic authentication with an API key.
  # Paths configured with api_key security require an API key for all requests.
  api_key:
    type: "apiKey"
    description: |-
      An API key for your client integration restricted to the Locate API and
      allocated using a self-service [signup](https://docs.google.com/forms/d/e/1FAIpQLSeWMiPSRWHIcg5GVRG-oc5kkefLpR4Nqk4aNYBFK6Wr8jAAdw/viewform)
      or allocated by M-Lab for your client integration.
    name: "key"
    in: "query"
