# Built the command using a golang base image.
FROM golang:1.18.3-alpine3.16 AS build
RUN apk add git
ADD . /go/src/github.com/m-lab/locate
RUN go install -v \
    -ldflags "-X github.com/m-lab/go/prometheusx.GitShortCommit=$(git log -1 --format=%h)" \
    github.com/m-lab/locate/cmd/heartbeat@latest

# Now copy the resulting command into the minimal base image.
FROM alpine:3.16
COPY --from=build /go/bin/heartbeat /
WORKDIR /
ENTRYPOINT ["/heartbeat"]
